[manifest]
id = "mm_recomp_discord_rich_presence"
version = "1.0.0"
display_name = "Discord Rich Presence"
description =  """
This mod reads the game state to tell discord if you are in Menus, Termina, or Hyrule(to be implmented)

github: https://github.com/ali-layken/MMDiscordRichPresence
"""
short_description = "Share Zelda64Recomp Activity on Discord"
authors = [ "SuperBeanEater3000" ]
game_id = "mm"
minimum_recomp_version = "1.2.2"
dependencies = []
native_libraries = [
    { name = "libdiscord_integration", funcs = [ "init_discord_client", "update_discord_client", "update_discord_rich_presence"]},
]                   
[inputs]
elf_path = "build/mod.elf"
mod_filename = "mm_recomp_discord_rich_presence"

func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

additional_files = []
